force-app/main/default/objects/Discount_Setting__mdt/fields/Class_to_Instantiate__c.field-meta.xml
<CustomField>
    <fullName>Class_to_Instantiate__c</fullName>
    <description>Apex Class implementation to be used for this discount setting</description>
    <inlineHelpText>Apex Class implementation to be used for this discount setting</inlineHelpText>
    <label>Class to Instantiate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Setting__mdt/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DiscountFactory.cls
public class DiscountFactory {

    public static IDiscount getDiscountInstance(String tier) {
        Discount_Setting__mdt discountSett = [SELECT Class_to_Instantiate__c FROM Discount_Setting__mdt
                                              WHERE Tier__c = :tier];
        
        Type t = Type.forName(discountSett.Class_to_Instantiate__c);
        IDiscount discountInstance = (IDiscount)t.newInstance();

        return discountInstance;
    }
}