force-app/main/default/objects/Discount_Setting__mdt/fields/Class_to_Instantiate__c.field-meta.xml
<CustomField>
    <fullName>Class_to_Instantiate__c</fullName>
    <description>Apex Class implementation to be used for this discount setting</description>
    <inlineHelpText>Apex Class implementation to be used for this discount setting</inlineHelpText>
    <label>Class to Instantiate</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Discount_Setting__mdt/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Discount percentage</description>
    <inlineHelpText>Discount percentage</inlineHelpText>
    <label>Discount</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BronzeDiscount.cls
public class BronzeDiscount implements IDiscount {

    public Decimal calculateDiscount(Decimal amount) {
        Discount_Setting__mdt discountSett = [SELECT Discount__c FROM Discount_Setting__mdt
                                              WHERE Class_to_Instantiate__c = 'BronzeDiscount'];

        Decimal discount = discountSett.Discount__c;
        
        return amount - (amount * discount);
    }
}